### ISSUE TITLE
Two Spring folders in File->New

### ISSUE THREAD

**Issue by luvalach** [spring-projects/spring-ide#139]
There are two "Spring" folders in "New" dialog (File -> New -> Other...) after installation of Spring IDE 3.9.0.201704032030-CI-B1634.  

Please note that there are items "Import Spring Getting Started Content" and "Spring Getting Started Content" which both point to same dialog.

**Comment by martinlippert** [comment]
It sounds like the update to the CI version left you with an installation that contains multiple versions of the tooling at the same time. Which version of STS did you have before? Something installed into Eclipse? Or the STS distro? And which version of those?

**Comment by luvalach** [comment]
I tried it again with clean Eclipse (Neon3 Build id: 20170314-1500). I didn't find any spring plugin in Help->Installation Detains and also File->New->Other didn't contain any Spring stuff.

So I installed "Core / Spring IDE" from http://dist.springframework.org/snapshot/IDE/nightly/. After restart I have two "Spring" folders in "New" dialog.

I have installed Spring IDE 3.9.0.201704032030-CI-B1634.

**Comment by martinlippert** [comment]
You are completely right, I tried this myself and it is indeed the case. This is also the case when you use the latest STS distribution download (3.8.4), so there must be a left-over from some refactoring in the extension definitions. Thats for finding that out. I think I usually use the context-menu in the Spring perspective (where this duplicate doesn't appear) instead of the general "New ->" menu... ;-)

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

This is fixed by introducing a new and separate category for Spring Boot (which makes sense anyway) and re-arrange the existing menu items into those categories.
