### ISSUE TITLE
annotation processing issue (reported to m2e-apt)

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/spring-ide#171]
There is an issue with annotation processing being configured in a wrong way in STS, as reported here: https://github.com/jbosstools/m2e-apt/issues/57

There is a sample project attached to that issue to reproduce the problem.

**Comment by Frettman** [comment]
The problem here is the lacking support for the *annotationProcessorPaths* configuration of the maven-compiler-plugin. STS will deactive annotation processing for an Eclipse project if it doesn't find an annotation processor in the Maven project's dependencies. And the advantage of *annotationProcessorPaths* is exactly that: you don't have to add processors as project dependencies.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Nieraj Singh:) 

I think this may be fixed. But would be good to get a confirmation from the original author of the bug that it got fixed

**Comment by martinlippert** [comment]
@Frettman can you check the latest nightly build and verify that this works now out of the box without the workaround? You can find nightly downloads at: http://dist.springsource.com/snapshot/STS/nightly-distributions.html

**Comment by Frettman** [comment]
I can confirm that the latest nightly of STS no longer disables annotation processing once **annotationProcessorPaths** is present. It's no longer necessary to disable STS's auto configuration of JDT APT.

**Comment by martinlippert** [comment]
Awesome, thanks for double checking and the feedback. Much appreciated!!!
