### ISSUE TITLE
detached views automatically moved to primary screen

### ISSUE THREAD

**Issue by dominik42** [spring-projects/spring-ide#193]
[stsEffect.m4v.zip](https://github.com/spring-projects/spring-ide/files/1316779/stsEffect.m4v.zip)
Since updating from macOS elCapitan to macOS Sierra I have a strange behaviour for detached views in my STS 3.9.0 / Java 8: Usually I detach the console view from the bottom of the STS application window and move that detached view window to my second screen. The STS application window remains on the primary screen. If I then later hover over e.g. a class name in Java Editor, the previously moved detached view windows is moved automatically to the primary screen, directly beside the small hover window with infos for the class. Attached you can find a screen recording video showing this effect. This is very strange and made the console view (and any other detached view) unusable on a second screen.

**Comment by martinlippert** [comment]
I think the reason is the macOS feature to assign a separate space to each screen. This sounds like your issue here: https://superuser.com/questions/669758/stick-floating-eclipse-windows-on-second-screen-with-mac-os-10-9-mavericks

I can reproduce this and when I disable the "use separate space per screen" feature in the maOS preferences, the console view stays on the second screen.

Hope this helps!!!

**Comment by dominik42** [comment]
yep, this macOS settings fix this annoying behaviour ... THANK YOU.
