### ISSUE TITLE
Linux version of STS unavailable for armv7l architecture 

### ISSUE THREAD

**Issue by ljv5555** [spring-projects/spring-ide#200]
Linux version of STS is unavailable for armv7l architecture **and** can not be installed into existing eclipse because STS Eclipse update site does not support Eclipse 3.8.1 (latest available supported version on this architecture).

This could be understandable if Oracle JDK were still unavailable for armv7l but this is no longer the case (Oracle has released JDK for 32-bit and 64-bit ARM in "Java SE Development Kit 8u77" and later versions).

**This is preventing STS from running on a "supported" operating system.**

**Comment by ljv5555** [comment]
associated Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=525528

**Comment by martinlippert** [comment]
The last version of STS that was compatible with Eclipse 3.8 was STS 3.6.3, which you can install from this update site: http://dist.springsource.com/release/TOOLS/update/e3.8

I will close this issue here since there is nothing special that we can do about that here for STS. As soon as there is a Eclipse version released for that platform, you should be able to install the latest STS releases into that via the Eclipse Marketplace. Please follow the bug at Eclipse for corresponding updates.
