### ISSUE TITLE
Debug Action Set not enabled for Debug Perspective in 3.9.1

### ISSUE THREAD

**Issue by gorbachev** [spring-projects/spring-ide#206]
After upgrading a 3.9.0 version to 3.9.1, the Debug Action Set is not active, meaning the debug actions, like stepping after pausing at a breakpoint, are not available in the IDE.

Additionally, the Debug Action Set resets back to unselected any time you switch away from the Debug Perspective and back. So every time you pause at a breakpoint you have to customize the perspective to enable the toolbar items. Even that doesn't seem to help all the time. Instead what appears to be happening is that the Action Set becomes unselected after you select and hit apply on the customize perspective dialog.

Those actions don't also have default keyboard shortcuts, so in default configuration, if your code execution pauses at a breakpoint, you're stuck.

**Comment by gorbachev** [comment]
Re-enabling the Debug Action Set from Customize Perspective works only the first time after restarting STS.

**Comment by kdvolder** [comment]
I cannot  reproduce this at all. Debug actions working normally for me. Are you running this with an old or new workspace? If an old workspace perhaps some workspace metadata has gotten corrupted. You could try a new workspace and see if that helps.

What OS are you on. The fact that you can't seem to make permanent changes to perspective reminds vaguely of problems reported in the past by mac user's caused by Mac OS startup folder randmization.

**Comment by gorbachev** [comment]
I just did a fresh install, and that one is working correctly. I think you're probably correct.

Running on Windows 7. The issues happened after upgrading 3.9.0 to 3.9.1 running against the old workspace. I didn't see anything related in the error log.

**Comment by kdvolder** [comment]
Okay, thanks for letting us know. Closing this ticket now. Let's hope it is an isolated case of something that mysteriously went wrong during update.
