### ISSUE TITLE
Suggestion: text selection on double-click for thymeleaf

### ISSUE THREAD

**Issue by foromix** [spring-projects/spring-ide#213]
Currently in STS, when double clicking the text in a thymeleaf syntax such as ${name}, it highlights the whole text including the ${} sign, I actually want to copy only the text itself, I have to re-select using mouse which is not so efficient... 

Is it possible to change this so that only the text will be selected? I think it is more developer friendly.

Thanks!

**Comment by martinlippert** [comment]
Thanks a lot for the feature request and the suggestion. Do you use an additional plugin for Eclipse that supports Thymeleaf? Since we don't work on special support for Thymeleaf in Eclipse, I wonder whether there is an existing plugin that could help you. I found this: https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin. Not sure if that is still in active development, but maybe worth a try and to file the feature request over there?
