### ISSUE TITLE
Cannot install buildship onto STS 3.9.2

### ISSUE THREAD

**Issue by rao-pathangi** [spring-projects/spring-ide#228]
Unable to install buildship via either of the three approaches below:

1. Eclipse marketplace
2. Install new software -> Oxygen software site (Oxygen - http://download.eclipse.org/releases/oxygen)
3. Buildship's download site @ buildship - http://download.eclipse.org/buildship/updates/e47/releases/2.x

Previously, option (2) above was mentioned as a solution. 

I get the following error with option (2)
```
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.gradleware.tooling.client,0.19.4.v20171108133209
No repository found containing: osgi.bundle,com.gradleware.tooling.model,0.19.4.v20171108133209
No repository found containing: osgi.bundle,com.gradleware.tooling.utils,0.19.4.v20171108133209
No repository found containing: osgi.bundle,org.gradle.toolingapi,4.3.0.v20171108133209
```

**Comment by rao-pathangi** [comment]
@khatchad's response below fixed the issue:
https://github.com/eclipse/buildship/issues/488#issuecomment-306801548

**Comment by martinlippert** [comment]
Ok, sounds like you got it working with the mentioned fix. In case you observe similar errors in the future (repository does not contain artifact), I would recommend to go to the preferences for the available updates sites, select the update site, and press "reload". Sometimes the above mentioned problem happens because of stale cache data for those repositories and the "reload" refreshes that.
