### ISSUE TITLE
Spring Starter Wizard freezes with custom Spring Initializer

### ISSUE THREAD

**Issue by dthommes** [spring-projects/spring-ide#230]
Hello, 
we have built a custom Spring Initializer derived from https://github.com/spring-io/initializr.
This initializer worked great with the old Spring Starter Wizard that was available e.g. in STS 3.7.3 and 3.8.0. 

With the new Spring Starter Wizard (available e.g. in 3.8.4 and 4.0.0.M7), our initializer does not work together, anymore. The wizard seems to get stuck in an infinite loop when the URL is changed from the default to our initializer's URL:
https://start.remoteui.org/

The wizard displays the following message and never activates the "Next" Button:
`Contacting web service and building ui model...`

In the down-right corner, STS infinitely displays the message:
`Building UI model`

The **Error Log View** does not show any problems or Exceptions. Therefore, we are not able to identify the problem. The only possibility is to exit STS.

It might be possible, that the problem is on our side - we are some commits behind the official initializr project. However, it would be great to know, where to search.

@martinlippert: Martin, we had a short talk on this issue in July on Java Forum Stuttgart. Thank you for your advice. I hope you can help us.

**Comment by kdvolder** [comment]
I will have to look into it. Please leave the https://start.remoteui.org/ up and running, I'll give it a try tomorrow and poke around with debugger inside of STS to try and see where it might be going wrong.

**Comment by martinlippert** [comment]
@dthommes great to hear back from you and thanks for the detailed report, much appreciated. As @kdvolder said, he will take a look.

**Comment by kdvolder** [comment]
I've determined what the problem is. The wizard is going into an infinite look trying to generate a 'valid' project name.

Newer version of the wizard checks whether the project name passes its validator (this was done so that if you repeatedly use the wizard it would generate a new name with a number `my-project`, `my-project-2`, ...` etc.  Instead of reusing the same name and show an error that project already exists in the workspace.

The validator doesn't like the name "Great App" returned by the custom wizard becuase it has a space in it. So it generate a new name "Great App-1", "Great App-2" etc. But all of these names are invalid -> infinite loop ensues.

I think there's a few lessons here. 

1. You should not put spaces in the project name.
2. We (STS) should not blindly loop forever trying to generate a project name.
3. STS should not generate new project name with spaces even if the service did suggest that as a default.

So here's what I'll do:

- fix the default value returned by the service by replacing all spaces by '-'.
- limit the 'name generation loop' to a few iterations to avoid infinite loops under any circumstances.

**Comment by kdvolder** [comment]
Reopened. Github decided to auto-close because of some commits. But we should wait to close until fix is verified in snapshot build. I'm also still in the process of pushing other half of the fix to a different repo.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Verified the fix from STS3 snapshot update site. Delivering.

**Comment by dthommes** [comment]
Hello Kris and Martin,

thank you very much for the investigation and fix! I have now removed the white space from the project name in our initializr as well. Now the wizard works great in all versions!

_Just an idea:_ Would it be an option to use the `artifactId` as (technical) project name in STS? The name field could then contain any character as long as the artifactId is valid. In our case "Great App" could be used for the name and "great-app" for the artifactId. Today, you can generate a project via http://start.spring.io entering a name that differs from the artifactId (Full version UI). The name appears in the pom's `name` element. When importing such a Maven project, STS takes the artifactId as project name.

Thank you and best wishes!

**Comment by kdvolder** [comment]
@dthommes Interesting suggestion. I think we could use the artifact id as project name, but it seems a bit odd then to have a 'name' field in the wizard.

>  The name appears in the pom's name element. When importing such a Maven project, STS takes the artifactId as project name.

Hmm... that's strange, perhaps we should consider that as a bug. (I'd expect it to use the pom name attribute). Though I guess unless someone really complains about it being a problem I probably wouldn't do anything to fix it.
