### ISSUE TITLE
Missing spring properties editor in STS 3.9.2 - no content assist

### ISSUE THREAD

**Issue by drsaxman** [spring-projects/spring-ide#232]
I recently installed STS 3.9.2 on a clean Eclipse Oxygen platform. After installing, the application.properties file no longer has the leaf associated with the applications.properties file. When I right click and go to Open with... there is not an option to choose the Spring Properties Editor. As a result, content assist does not work in the applications.properties file.

**Comment by psevestre** [comment]
Same thing here. Eclipse Oxygen.2 (4.7.2) and STS 3.9.2.201712210913-RELEASE.

Besides application.properties, content assist is not working anymore for yaml files.

**Comment by kentkwan** [comment]
Version: Oxygen.2 Release (4.7.2) Build id: 20171218-0600

**Comment by BoykoAlex** [comment]
Will have a look at this today at the end of today

**Comment by kdvolder** [comment]
> I recently installed STS 3.9.2 on a clean Eclipse Oxygen platform

Can you elaborate more precisely what you did? There are a number of different ways to install STS into an existing Eclipse. E.g. when you install using an update site it is possible to select some bits and pieces and not others.

It sounds like somehow some bits are not getting installed. This may depend on precisely how you installed things and the exact selections of features you made if you were using an update site.

**Comment by psevestre** [comment]
In my case I made a clean Eclipse Oxigen install followed by STS install
from the update site. IIRC, I've used the default set of features. I'll try
to reproduce the steps for a new install and see if the issue persists.



Em 15 de jan de 2018 15:37, "Kris De Volder" <notifications@github.com>
escreveu:

I recently installed STS 3.9.2 on a clean Eclipse Oxygen platform

Can you elaborate more precisely what you did? There are a number of
different ways to install STS into an existing Eclipse. E.g. when you
install using an update site it is possible to select some bits and pieces
and not others.

It sounds like somehow some bits are not getting installed. This may depend
on precisely how you installed things and the exact selections of features
you made if you were using an update site.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/spring-projects/spring-ide/issues/232#issuecomment-357747716>,
or mute the thread

**Comment by kdvolder** [comment]
Note: I just stumbled on this (catching up on all my mail after a little vacation). This seems to say installing from marketplace results in this issue too:

https://stackoverflow.com/questions/48093885/eclipse-spring-tools-missing-content-assist-autocomplete

**Comment by kentkwan** [comment]
The same environment with springsource-tool-suite-3.9.1.RELEASE-e4.7.1a-updatesite.zip to replace 3.9.2.RELEASE is work. 
The file you will find in this [http://download.springsource.com/release/TOOLS/update/3.9.1.RELEASE/e4.7/springsource-tool-suite-3.9.1.RELEASE-e4.7.1a-updatesite.zip](url)

**Comment by martinlippert** [comment]
I think I found the reason for this: Due to a small refactoring in the feature structure, the property editing support is now part of a different feature than before. And this new feature is missing from the marketplace install definition, therefore you don't get that from the marketplace at the moment. I will go ahead and fix that.

In addition to that if you installed the Spring Tools from the marketplace in the past and updated that install to the latest STS 3.9.2, you probably lost the property editing support due to this move between features. In that case, please go to `Install New Software`, select the Spring Tools update site (that you already have in the list), expand the `Extensions / Spring IDE` section and install `Spring IDE Boot Support` feature. It will bring back the property editing support.

**Comment by psevestre** [comment]
Fixed after selecting the missing feature. Thanks !

**Comment by martinlippert** [comment]
Glad to hear the fix works for you and thanks for letting us know and the details in the report here. Sorry for the inconvenience!!!

**Comment by ronaldocaldas** [comment]
@martinlippert  i did what you told, but now all the assistent editor dosen't works less for .properties files...

**Comment by martinlippert** [comment]
@ronaldocaldas It is somewhat hard to tell what went wrong here, but I will give it a try... :-) So what version of STS do you have? And probably updated from what version? And you did install the feature mentioned above, right? From which update site?

Does the Spring Properties Editor shows up when you select the `application.properties` file with `Open With...` ? And if you open that, what happens?

**Comment by ronaldocaldas** [comment]
@martinlippert I was tryng with a older version of STS, i remove that version, deletes the .metadata from my workspace and installed the 3.9.4.RELEASE with Spring IDE Boot Support by SpringSource Update Site for Eclipse 4.7 - http://download.springsource.com/release/TOOLS/update/e4.7. Now the pom.xml completation assistent is not working, but i can live without it.. Thanks

**Comment by martinlippert** [comment]
@ronaldocaldas Sounds good that you got most of the Spring features working again, but the broken pom.xml completion sounds suspicious nevertheless. What version of Eclipse did you use to install the 3.9.4.RELEASE of the Spring Tools into? Would like to reproduce this issue locally to take a deeper look.

As a side note, you can always download a ready-to-use distribution of STS 3.9.4 from https://spring.io/tools/sts/all, it is based on the latest Eclipse release and contains an Eclipse distribution with Spring Tools pre-installed.

**Comment by ronaldocaldas** [comment]
@martinlippert thanks again for the quicly feedback, i downloaded the MAC version from the site spring.io based Based on Eclipse 4.7.3a and download Spring IDE Boot Support from Install New Software ->Update Site for Eclipse 4.7 - http://download.springsource.com/release/TOOLS/update/e4.7. I also heve the all Maven Ingregration software install as show the image below...
![captura de tela 2018-05-15 as 10 37 58](https://user-images.githubusercontent.com/12235076/40060145-4c66d964-582c-11e8-95b5-195a174f9b16.png)

**Comment by martinlippert** [comment]
If you download a ready-to-use STS distribution from https://spring.io/tools/sts/all, you don't need to install anything else from the update site (and you should not do that). And when you try to do that, it should tell you that this feature is already installed.

Can you maybe attach a sample project and a few steps that reproduce the setting that doesn't work?

**Comment by ronaldocaldas** [comment]
@martinlippert  really strange  because im tryng  with a ready-to-use STS distribution, and since the first intallation i has the same problem, no autocomplete on .properties files. Now im working on a project with angular so im using visualstudio for while. But I started a springboot project and tried typing "spring". in my application.properties file, and nothing happened.

**Comment by ronaldocaldas** [comment]
Thanks  @martinlippert  i restart eclipse and now it's working, i had a doubt about the bahavior of content assist, basicly what is the diference between  Basic Proposals, Java proposals, Java proposals Non-Type Proposals,  Java proposals (code Recommenders)? i work with with Java Spring Boot  with Web dependencies,  this is my config: 
![captura de tela 2018-05-31 as 11 06 25](https://user-images.githubusercontent.com/12235076/40787313-acf3ddce-64c3-11e8-9380-a9048f085afa.png)

**Comment by martinlippert** [comment]
Those are the regular content-assist settings that are contributed by the various extensions to the Java editors - and I agree, that list can be quite confusing. But they don't interfere with the content-assist you are getting for application.properties, which is purely provided by the Spring tools.

Usually, the standard settings are just okay for you to go (in the Spring Boot web app context).
