### ISSUE TITLE
Package import not recognized, nor any of its public classes.

### ISSUE THREAD

**Issue by alevele3** [spring-projects/spring-ide#247]
I recently installed Eclipse Oxygen Eclipse Java EE IDE for Web Developers.
Version: Oxygen.2 Release (4.7.2)
Build id: 20171218-0600
OS: Mac OS X, v.10.13.3, x86_64 / cocoa
The package import does not work, nor the CTRL + SHFT + O.

**Comment by alevele3** [comment]
Well, this is weird; I copy the class to be used and added to a bran new package just created named ’testing'. Imported it, and it worked.

**Comment by alevele3** [comment]
I created a new package, named it 'TESTING', added the intended class to be instanced, imported to the main class, no errors, It worked.

Weird!

**Comment by kdvolder** [comment]
Sounds like it could be a classpath issue. Classpath maybe was not ready. Or maybe Eclipse was still indexing the classpath (so that it can find existing types in it). 

It is just a guess, but if I'm right its more or less normal/expected behavior. Some functionalities only work when classpath is known/resolved and its types are indexed by JDT search engine.

If you run into the problem again and find a way to reproduce it, please add some steps for us to try and we can have another deeper look at it.

In the mean time, I'm closing the ticket. (But of course can be reopened if you add more information to reproduce).
