### ISSUE TITLE
Application properties editor doesn't show line/column info

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-ide#250]
When using the application properties editor I notices that the line/column info isn't displayed in the status bar. If I use the regular text editor it is.

I don't use show line numbers so this info is very useful to me.

**Comment by martinlippert** [comment]
This is fixed in master, but hasn't made it into the 3.9.3 release. If you want to get it now, feel free to grab the latest 3.9.4.CI build for Eclipse 4.7.3 from here: http://download.springsource.com/snapshot/STS/nightly-distributions.html or update your install using the nightly p2 repos mentioned there.
