### ISSUE TITLE
Use https by default

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-ide#255]
The plugin seems to contact `http://start.spring.io` rather than `https://start.spring.io`. Please use the latter.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

To change the 'original source' of this value is actually pretty trivial. Just a one liner changing a string constant. 

However, unfortunately 'shadow' copies of the url could be stored in a number of places in workspace. I.e. if I open an existing workspace in which I have used the wizard before. The dialog state contains a copy (because it remember old values for 'auto-fill'. Also default value is a preference so another copy could be stored in workspace preference too.

There may be other places that remember the old url in user's workspace somewhere.

So besides changing the string constant I will also add some logic to the dialog's initialization to catch the old value and replace it with the new one automatically.
