### ISSUE TITLE
New Spring Starter wizard doesn't follow redirections from http to https url

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-ide#260]
See: https://github.com/spring-io/initializr/pull/625#issuecomment-376567079

Note: We have already made sure the for the default `start.spring.io` we always use https no matter what. (See https://github.com/spring-projects/spring-ide/issues/255). But redirects might still be an issue for people deploying their own custom version of the web service.

This is probably a minor convenience (user just has to use the https url directly and then it all should work).

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Fix pushed. Note that both 'New Spring Starter' and 'Edit Starters' are affected by this. I fixed both of them.

The fix makes it so that creation of the InitializrSpec' from the url throws a execption when the url is being redirected. The wizard model handles the exception and automatically changes the 'service url' input field to the
redirected url.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Note to Martin: to verify this in accept test... you can use this url to test with: `http://start-development.cfapps.io/`.

As the http redirect is being handled, the url in the wizard should automatically be changed.

Also... this bug affected both the **New Spring Starter' wizard and **Edit Starters** in a slightly different way. Both should now follow the redirect and change the url in the wizards input field automatically.
