### ISSUE TITLE
Can't install AJDT into STS 4.0.0 M10

### ISSUE THREAD

**Issue by ahoehma** [spring-projects/spring-ide#270]
I try to install latest ajdt from http://download.eclipse.org/tools/ajdt/47_aj9/dev/update
but (as far as I understand) this ajdt version doesn't support 
org.eclipse.jdt.core.manipulation >= 1.10.0 (which seems to be the current SNAPSHOT version of JDT).

Could it be that STS is included the latest JDT snapshot version?

More details here in the adjt forum: https://www.eclipse.org/forums/index.php/m/1785489/

**Comment by martinlippert** [comment]
Looks like this issue is for STS4 (using STS 4.0.0 M10), so should be reported here: https://github.com/spring-projects/sts4/issues

STS4 builds are based on Eclipse Photon (4.8), so I think you need an Eclipse-4.8-compatible version of AJDT. The latest dev updates for e47 doesn't seem to be compatible with the latest 4.8 versions of Eclipse anymore.

**Comment by ahoehma** [comment]
Ah this was a good hint @martinlippert  :) Thanks
