### ISSUE TITLE
can't download STS

### ISSUE THREAD

**Issue by alexander-zakharov** [spring-projects/spring-ide#274]
getting this:
File Transfer Blocked
Transfer of the file you were trying to download or upload has been blocked in accordance with company policy. Please contact your system administrator if you believe this is in error.

File name: artifacts.jar

**Comment by martinlippert** [comment]
Looks like you tried to install STS into an existing Eclipse installation. As an alternative, you could try to download a ready-to-use STS distribution from https://spring.io/tools/sts/all.

In addition to that you should maybe take into account the advice that the error message provides: talk to your system administrator and discuss why that file has been blocked - since that is nothing that we can influence.
