### ISSUE TITLE
Docker Build fails

### ISSUE THREAD

**Issue by mihaita-tinta** [spring-projects/spring-ide#302]
From the latest STS if you download a simple http source from http://start-scs.cfapps.io/ and run a docker:build you get the error below:

`Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing io.fabric8:docker-maven-plugin:0.26.1:build: org/fusesource/jansi/Ansi$Color`

The same issue is opened here, but it looks like the problem is with the embedded maven?

https://github.com/fabric8io/docker-maven-plugin/issues/1042

Thanks.

**Comment by kdvolder** [comment]
> The same issue is opened here, but it looks like the problem is with the embedded maven.
From browsing the issue, it seems like yes. 
BTW: http://start-scs.cfapps.io/ link doesn't seem to lead anywhere (404 error).

I'm closing this ticket as it doesn't seem like something we can fix. You can re-open it however and add more details to the ticket if you think there is something we can do.

BTW: the ticket mentioned that some folks have been able to work around the issue by using an external maven distribution instead of the embedded one that ships with Eclipse. So that maybe something you can try as well.
