### ISSUE TITLE
STS crashing consistently with probable disk utilization problem

### ISSUE THREAD

**Issue by mihir190** [spring-projects/spring-ide#304]
I unable to use STS  3.9.5 release with jdk_1.8_144.I am using Windows 10 machine.

I have tried changing workspace it doesnt work.
I have tried the same with 3.9.0 release it crashes.It used to work uptil 1 year.
I have also tried changing projects it doesn't work.I have monitored the memory using task manager of windows it seems to be  fine.

[logFile.txt](https://github.com/spring-projects/spring-ide/files/2222426/logFile.txt)
I am attaching the log files.

**Comment by mihir190** [comment]
On deeper look whenever STS starts utilizing file system the mcafee scanner starts running and a lot of times disk utilization increases to 99%.Not always.STS logs may not be printing this.Can we check this by introducing some logs ??

**Comment by mihir190** [comment]
One more thing I tried the operations I w as performing on another IDE Visual Code.The disk utilization did not increase.

**Comment by mihir190** [comment]
No I see the UI.I perform two operations one is forcing maven update or opening a specific file in project.It crashes in both cases

**Comment by mihir190** [comment]
So I typically close the dashboard to avoid unnnecesary processing.But I have disbaled it with some configurations.I dont remmeber how did I do that.Yes windows update keeps happening every 15 days

**Comment by kdvolder** [comment]
> Can we check this by introducing some logs ??

Not really sure how/what we should be logging.

As Alex pointed out your attached log is full of errors related to SSL certificates. Not sure that could be responsible for the crash, but it does seem to be an indication something is wrong and various Eclipse components are having a hard time accessing network resources.

As to disk activity, when doing a maven update, that is kind of expected since it will cause all project dependencies to be checked / refreshed / downloaded in the maven cache on disk. If you have a Virus scanner trying to scan all those massive amounts of files that maven touches / downloads / updates, I could imagine that can put quite a lot of stress on your system.

**Comment by mihir190** [comment]
Updating Java did provide a relief.But not upto the mark.STS is still crashing

**Comment by mihir190** [comment]
Is there a way to prove that it is a windows issue ??So that I can atleast raise it there. The place where I work there are repeated instances of breaking of applications because of microsoft update.

**Comment by kdvolder** [comment]
> Is there a way to prove that it is a windows issue ??
Well... not really. Even if its somehow a Windows-specific problem that doesn't mean it is a 'Windows issue' in the sense that it is wholly Window's fault. Unless we really understand why something is happening it is kind of impossible to say who/what is to really blame.

Maybe you can do a bit of experimenting to narrow down what the cause might be. These are some ideas:

- (temporarily) disable virus scanner and see if it makes a difference.
- (temporarily) disable any firewall software / rules that might interfere with network connections
- running STS on a different computer (e.g. a Linux VM, a laptop not within your corporate network on a more open network environment).

BTW: You keep saying that STS 'crashes' but haven't really said exactly what that means. Does the process 'just close'? Spit out a lot of errors? Hang and force you to kill it?

There are different ways of 'crashing' so some details might be useful. For example if it is a JVM crash, then usually there would be some crashlog created somewhere containing more details abotu the state of the JVM at the crash (this is not the same log as what you posted already, which is a log file from Eclipse itself, the JVM crashlog comes directly from the JVM itself).

See: https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/felog001.html

So look for a file with a name like `hs_err${pid}.log` where `pid` is a process-id (so a number).

**Comment by mihir190** [comment]
![untitled](https://user-images.githubusercontent.com/31958935/43306571-3f517332-9199-11e8-934b-6ea6c7b265a7.jpg)
This is what happens.Clicking on close button and close program causes STS to close down.

**Comment by mihir190** [comment]
Most of those files are wiped off.And new files are not getting generated.But I have two files left with me.From the time where this problem started coming.This was in STS 3.9.0

[hs_err_pid10420.log](https://github.com/spring-projects/spring-ide/files/2234874/hs_err_pid10420.log)
[hs_err_pid23756.log](https://github.com/spring-projects/spring-ide/files/2234875/hs_err_pid23756.log)
[replay_pid10420.log](https://github.com/spring-projects/spring-ide/files/2234876/replay_pid10420.log)
[replay_pid23756.log](https://github.com/spring-projects/spring-ide/files/2234877/replay_pid23756.log)

**Comment by mihir190** [comment]
The last one I have is this 
[hs_err_pid10760.log](https://github.com/spring-projects/spring-ide/files/2234878/hs_err_pid10760.log)
[replay_pid10760.log](https://github.com/spring-projects/spring-ide/files/2234879/replay_pid10760.log)

**Comment by BoykoAlex** [comment]
Judging from `hs_err_pid0760.log` you don't have enough RAM on your system to run the STS process... The header states that.
What are the `-Xms` and `-Xmx` args value in `STS.ini` file? (if args are present)
Wonder if you were running out of memory with any other processes on this machine...

**Comment by kdvolder** [comment]
> Judging from `hs_err_pid10760.log`.

From the looks of that file, the carshed process, was running maven, not STS. Probably an embedded maven instance that crashed.

I'm not sure old logs are going to be very helpful in determining a current problem. We don't really know if these logs are actually related/relevant to the current problem. It would be better if we had logs that actually appeared at about the same time of the crash.

From what you describe, it sounds more as if Windows 10 is terminating STS for some reason (because there is no crashlog, and it sounds like STS is still there until you click the dialog to terminate it). It is really too bad that the message isn't more specific about why Windows 10 thinks STS process should be terminated STS. I googled a bit around that kind of dialog but didn't really find anything helpful.

If I find some time later I will try to run STS on a Windows 10 VM to see if I get any similar problems.

**Comment by mihir190** [comment]
Thanks guys for your help.I increased the page size of application in OS.For disk utilization problem I cleared the temp folder of windows it was more than 2 GB. STS has now stopped crashing.We have a tool in GE which does not allow partial updates to install on machine.So it was never a windows update issue

**Comment by kdvolder** [comment]
Glad you figured it out. Thanks for letting us knows.
