### ISSUE TITLE
Out of the box STS 3.9.5 on Mac does not install Gradle support

### ISSUE THREAD

**Issue by tedyoung** [spring-projects/spring-ide#305]
Just downloaded and installed STS 3.9.5 for macOS. I was under the impression that Gradle support was part of this suite as "Gradle integration" is explicitly mentioned at the bottom of https://spring.io/tools/sts. (This is also taken for granted in this guide: https://spring.io/guides/gs/sts/).

After looking around for it on the `File > Import...` dialog, I did not see Gradle.

After searching around, it seems like Buildship needs to be installed, so I bring up the Dashboard, click on IDE Extensions, but when I search for Gradle, the list of tools is empty.

I have Gradle working properly from the command-line, and the project builds fine that way.

I found this page, https://marketplace.eclipse.org/content/buildship-gradle-integration, and finally figured out that I could drag-n-drop the "install" button, but when I do that, I see:

![image](https://user-images.githubusercontent.com/382660/43613408-194f911c-9664-11e8-8809-e81c36d71098.png)

Which is a bit confusing, since it says "Buildship ... 2.0", whereas the latest version of Buildship appears to be 2.2.1, so I didn't know if it was installing the latest version.

I went ahead anyway, and it *did* install the 2.2.1 release.

All this took a lot of time for me to figure out how to get Gradle support into my STS install. I feel like this should be more clearly documented on the STS install page.

Maybe this is assumed knowledge for those with Eclipse experience, but it was frustrating for me, especially as the out-of-the-box experience meant I couldn't import my Gradle-based project.

**Comment by kdvolder** [comment]
I agree that is a bit of unsatisfying first experience. Sorry about that :-) And thanks for taking time to report it. For STS 4 BuildShip is/will be included by default. I just checked our latest milestone build and that is already the case there. So this problem will kind of be fixed that way.

I'll eave this ticket open for now because we may still want to have a look at doing something in STS 3.9.x line, though it is kind of close to the end of the line. It may still be worthwhile to add a BuildShip entry to the 'IDE extensions' page that you were looking at to try to find it.

For future reference. When I need to install BuildShip I tend to use the Eclipse Marketplace which is fairly easy (once you know where/how to find it).  You can do it via the website as you did or via Eclipse help menu ("Help >> Eclipse Marketplace ..."). A wizard opens, then you type 'BuildShip' in the searchbox, and install.

The strange number 'BuildShip 2.0' that shows on the marketplace install is likely a problem with BuildShip's marketplace entry and not something we can fix (it is something only the owner of that marketplace entry can fix, so that is the BuildShip folks themselves).

**Comment by tedyoung** [comment]
I'm glad to hear this'll be solved with STS 4.

I didn't even look closely at the Help... menu, because other apps I use don't put functionality like that there, so seeing it there was...unexpected.

Honestly, even if there was a couple of sentences somewhere on the install page saying "For Gradle support, do the following..." that would've saved me a couple of hours of going down dead-end roads.

I'm surprised that the STS Extensions (from the Spring Dashboard) would have left out Gradle, given its importance/prominence. ☹️

**Comment by martinlippert** [comment]
I added Buildship to the default distribution of STS3 builds, so STS 3.9.6 will include it out-of-the-box. I also added Buildship to the list of extensions on the STS dashboard, for your convenience.

Therefore closing this item here.
