### ISSUE TITLE
An error occurred during the  org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.

### ISSUE THREAD

**Issue by jjarauta** [spring-projects/spring-ide#311]
When trying to install STS in an existing Eclipse installation I get the above error message with the following explanation:

session context was:(profile=C__Users_Javi_eclipse_jee-photon_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: C:\Users\Javi\.p2\pool\plugins\org.springsource.ide.eclipse.commons.livexp_3.9.6.201808291957-CI-B411.jar

This happens either I try the installation from the Market Place or from Installing New Software
 using the following link: http://download.springsource.com/release/TOOLS/update/e4.8/

I have check the bundle pool with the Analyze Agent and I get the following damaged artifact

![image](https://user-images.githubusercontent.com/33860514/44859193-ed76c300-ac73-11e8-8172-85b1c229836c.png)

So I repair it (it seems the tool just delete it).

![image](https://user-images.githubusercontent.com/33860514/44859486-8b6a8d80-ac74-11e8-8ba5-6311aa747418.png)

I try the installation again and keep getting the same error. It seems that each time I install STS, the installation gets the damaged artifact again.

**Comment by kdvolder** [comment]
I just installed STS 3.9.5 from the marketplace into a fresh 'eclipse-jee-photon' distribution package. I  did get a warning that one of our bundles is not signed (...commons.eclipse.ls bundle). This is something we should probably look into. Other than that though, the install seemed to have gone without a hitch.

From what you describe it sounds like there is something wrong with the livexp bundle's jar file. But since it installs and works fine for me, that doesn't actually seem to be the case.

If you are getting a bad version of that bundle I don't know where it might be coming from. Maybe something/someone is caching it somewhere.

BTW: I did not use the Oomp installed version of Eclipse, but 'jee' eclipse package instead. Not sure it makes a difference, but I could imagine that some Oomph magic is picking up bundles from a cache somewhere. Or perhaps the cache is somewhere else (network?). 

Anyhow... a lot of guessing here. But as far as I can tell there is no problem with the update-site and the marketplace entry so I'm not really sure why its not working for you. Maybe you can try installing it in a 'clean' environment. Perhaps under a different user account, a clean virtual machine, another laptop, something like that. Just to check if that works (in which case it provides more evidence there's someplace in your environment caching a damaged copy of the bundle).

**Comment by kdvolder** [comment]
Took another look at your screenshot. The 'broken' artefact it shows has a version that indicates it comes from a snapshot build. This is interesting but a bit puzzling. That artefact most definitely did not come from a release update site or marketplace entry. The version that I get installed from marketplace is:

```
org.springsource.ide.eclipse.commons.frameworks.core (3.9.5.201807030629-RELEASE)
```

Still a bit of mystery where you are getting the broken version from.

**Comment by jjarauta** [comment]
Hi Kris,
do know how but it worked now.
Thanks for your helping
Regards
Javier

**Comment by kdvolder** [comment]
Okay, thanks for letting us now. Glad it is resolved for you.
