### ISSUE TITLE
Spring Boot configuration property auto-completion does not offer properties on super classes

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-ide#315]
When auto-completing `spring.security.oauth2.client.registration.login.mylogin.` only two properties are offered: `redirect-uri` and `redirect-uri-template`. These are both on `org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientProperties.LoginClientRegistration`. However, `LoginClientRegistration` inherits several other properties from `org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientProperties.BaseClientRegistration` but these are not offered by auto-completion. I am using 3.9.5.201807030714-RELEASE.

**Comment by martinlippert** [comment]
@kdvolder Can you take a look?

**Comment by kdvolder** [comment]
I remember cutting a corner there. So I can confirm we don't currently examine the type hierarchy to find additional bean properties in inherited methods.

Is this fixable, I'd say yes. Might pose a little challenge because operations on the type hierarchy, can be a little expensive to do during a completion request.

I'll try today a bit to see how hard it be to fix in a branch.

**Comment by kdvolder** [comment]
Closing in favor of: https://github.com/spring-projects/sts4/issues/116
