### ISSUE TITLE
Java exit code 13 on startup

### ISSUE THREAD

**Issue by tedepstein** [spring-projects/spring-ide#320]
I have just downloaded STS 3.95.RELEASE for Windows from https://spring.io/tools. 

I'm running Java 8, 64-bit. 

```
C:\Users\tedep>java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

When I try to launch STS.exe, I get the following error message:

```
---------------------------
STS
---------------------------
Java was started but returned exit code=13
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\javaw.exe
-Dosgi.requiredJavaVersion=1.8
-Xms40m
-Dosgi.module.lock.timeout=10
-Dorg.eclipse.swt.browser.IEVersion=10001
-Xmx768m
-jar C:\Users\tedep\Downloads\sts-bundle\sts-3.9.5.RELEASE\\plugins/org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar
-os win32
-ws win32
-arch x86
-showsplash
-launcher C:\Users\tedep\Downloads\sts-bundle\sts-3.9.5.RELEASE\STS.exe
-name STS
--launcher.library C:\Users\tedep\Downloads\sts-bundle\sts-3.9.5.RELEASE\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_1.1.700.v20180518-1200\eclipse_1705.dll
-startup C:\Users\tedep\Downloads\sts-bundle\sts-3.9.5.RELEASE\\plugins/org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar
--launcher.overrideVmargs
-exitdata 3464_c8
-product org.springsource.sts.ide
-vm C:\Program Files (x86)\Common Files\Oracle\Java\javapath\javaw.exe
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms40m
-Dosgi.module.lock.timeout=10
-Dorg.eclipse.swt.browser.IEVersion=10001
-Xmx768m
-jar C:\Users\tedep\Downloads\sts-bundle\sts-3.9.5.RELEASE\\plugins/org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar 
---------------------------
OK   
---------------------------
```

So far, I haven't found likely reason for this in the README, nor in recent StackOverflow answers. Any help appreciated.

**Comment by tedepstein** [comment]
Thanks, @martinlippert !  Indeed, that was the problem. 

https://spring.io/tools/sts/all has both 32- and 64-bit installers. 

https://spring.io/tools is for the 32-bit version only. It might be a good idea to include that information on or near the download button.

**Comment by martinlippert** [comment]
Glad to hear that we found the reason here. And thanks a lot for the suggestion and I agree, would be good to have a hint on that page, too (or to take the platform architecture into account when showing the default download version on that page). But we are moving towards the release of STS4, the existing pages will be deprecated sometime soon and be replaced with the main page for STS4 (which will have 64bit downloads only). Therefore I tend to not modify the existing pages for now, focus on the new ones, and will close this item here. Hope that is fine with you.
