### ISSUE TITLE
Can't run 3.9.6 on Windows 10

### ISSUE THREAD

**Issue by Oscar-21** [spring-projects/spring-ide#322]
![image](https://user-images.githubusercontent.com/21151259/45911938-e90f7700-bde7-11e8-9fbf-9d044d900415.png)

**Comment by martinlippert** [comment]
This looks very much like an issue with the JDK that got picked and the STS version. Your path looks like it is using a 32bit version of the JDK as well as a 32bit version of STS, so that would be fine, but you should double check whether the JDK in that path is really a 32bit full JDK. And I would recommend to use the 64bit version of both (the JDK as well as STS) nowadays.

Beyond that you should double check which version of the JDK is being used here. I am asking all these questions because the path to the JDK in the error output looks a bit unusual.

If you have a specific JDK installed that you want to use, please configure the STS.ini file to pick exactly that JDK (java executable), like described here for Eclipse (therefore eclipse.ini in that doc): https://wiki.eclipse.org/Eclipse.ini

**Comment by Oscar-21** [comment]
Oops. I didn't mean to download the 32 bit version. Thanks for the help. 👍

**Comment by martinlippert** [comment]
Glad to hear I could help! :-)
