### ISSUE TITLE
Quise instalar Hibernate y tuve el siguiente error

### ISSUE THREAD

**Issue by JandroMejia97** [spring-projects/spring-ide#326]
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.ianbrandt.tools.m2e.mdp.core,0.0.4.201410161303
No repository found containing: org.eclipse.update.feature,com.ianbrandt.tools.m2e.mdp.feature,0.0.4.201410161303

**Comment by martinlippert** [comment]
I would appreciate if you could translate the title into english, so that others (and myself) can understand what you mean.

From the error report that you added as a description I vaguely guess that this is a installation issue, caused by a network glitch and stale/broken cached data for the update repositories. To solve this, you can remove those update sites from your Eclipse/STS installation, restart Eclipse/STS, and add them back. The easy way to remove and re-add them is to export them from the preferences, delete them all, restart, and import all of them back.

Hope this helps!
