### ISSUE TITLE
Error 0x80010135: Path too long

### ISSUE THREAD

**Issue by vk46** [spring-projects/spring-ide#330]
![sts_error](https://user-images.githubusercontent.com/17341864/49159994-c64f9080-f34b-11e8-87fe-3e3ef04b8d6c.png)

**Comment by vk46** [comment]
Failed to load the JNI shared library and some local path of jvm.dll file

**Comment by kdvolder** [comment]
Please provide some context. *When* does this error happen? In other words, what do we need to do to make it happen? I have used STS on Windows on occasion and never seen this problem so I don't know how to reproduce it (which also means I cannot figure out exactly why it happens, or if/how we could try to fix it).

**Comment by vk46** [comment]
Yeah, After downloading STS from website, I tried to unzip bundle that time I have seen above error alert. And after unzip completed after couple of skips of error, I'm unable run (Open) STS application. I have see this error while running application "Failed to load the JNI shared library and some path of jvm.dll file" and it's not opening because of some issues. Thanks in advance @kdvolder

**Comment by kdvolder** [comment]
Not sure what happened to this comment. I got it only in email but it seems to be in reference to this issue:

> Yeah, After downloading STS from website, I tried to unzip bundle that time I have seen above error alert. And after unzip completed after couple of skips of error, I'm unable run (Open) STS application. I have see this error while running application "Failed to load the JNI shared library and some path of jvm.dll file" and it's not opening because of some issues

Okay I understand now. 

I think its a limitation of Windows zip/unzip utility. THe built-in zip that comes with Windows is basically a poorly implemented unzip tool that can't deal with some of the longer pathnames in package. And so the zip file is not expanded correctly.

This problem can be avoided by using a better zip utility than the one that comes built-in with Windows. For example 7zip I beleave works fine. Or even simply using the 'jar' commandline tool that comes with Java can properly unpack the STS distribution zip without problems. I usually use `jar` on Windows myself because, since I already have Java installed I don't need to download anything extra. You can expand the zip using a command like this: 

```
jar xf <path-to-zipfile>
```

**Comment by GarryBrown88** [comment]
The **LongPathTool** is the very best program for error, unlock solution. Try it and solved your problem. I used the long path tool and I solved my error, unlocks problem solution.

**Comment by KevinNelson0700** [comment]
Exactly, I came to face this issue also. Then some recommended me Long Path Tool software and I am grateful to that person

**Comment by ynnenu** [comment]
I was facing the same problem. I got so comfortable with LongPathTool, I won't trade it for anything.

**Comment by elijahfrankinson** [comment]
Use LongPathTool it will solve your problem of deleting and copying long path files
https://longpathtool.com
