### ISSUE TITLE
Is it possible spring ide base on IDEA community?

### ISSUE THREAD

**Issue by netroby** [spring-projects/spring-ide#332]
Is it possible spring ide base on IDEA community?
Other than eclipse, IDEA was a better Editor and IDE tools

**Comment by martinlippert** [comment]
Spring IDE and the Spring Tool Suite 3.x are not available for IntelliJ and we don't have any plans to port Spring IDE parts or STS3 parts over to IntelliJ. IntelliJ comes with awesome support for Spring in their Ultimate edition, you should take a look at that if you prefer working with IntelliJ.

We have simple prototypes implemented for Spring Tools 4 for IntelliJ, but that is more an experimental prototype work rather than an official plan to fully support IntelliJ with Spring Tools 4.
