### ISSUE TITLE
STS 4.1.1 throws error "Application not found" creating or updating sql files in src main resources

### ISSUE THREAD

**Issue by matteg** [spring-projects/spring-ide#343]
When using new file schema.sql or data.sql from src/main/resources an error window appears stating "Application not found".  When creating the file (schema.sql) the file IS created but it can not be opened - the same error is thrown.

The workaround is to exit STS, edit the file using a text editor, then restart STS

The files are then processed properly using Spring Boot 2.1.2

**Comment by martinlippert** [comment]
First of all, I am sorry for the long delay in responding. Please accept my apologies.

The underlying reason for that seems to be the fact that STS 4 doesn't come with the Eclipse Data Tools installed out-of-the-box. Therefore there is no specific editor associated with `.sql` files or even more specifically with `schema.sql` files. As a result, the underlying Eclipse platform tries to open the "system editor" for those files, calling out to the operating system to run the corresponding editor for this file. This seems to go wrong in your case, resulting in that "Application not found" message.

In order to change that, there are two options that I haven in mind:

- go to the `Preferences -> General -> Editors -> File Associations` and create a new file/editor association for `schema.sql` files, for example by choosing the standard text editor for it. That doesn't give you any advanced editing capabilities, but it would result in this editor being used to edit the file instead of going to the OS to ask for an editor. You could stay working in your IDE.

- the other option would be to install the Eclipse Data Tools extensions via `Install New Software`, then selecting the main Eclipse download repository, and search for `Data Tools`. That provides a nicer editor experience for SQL files directly integrated into your IDE.

Hope this helps!!!
And sorry again for the long delay.
