### ISSUE TITLE
The save participant 'org.eclipse.jdt.ui.postsavelistener.cleanup' caused an exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by wamaco** [spring-projects/spring-ide#364]
I have encountered the same issue [https://jira.spring.io/browse/STS-4222](https://jira.spring.io/browse/STS-4222) , and I use Spring Tool Suite 4, which eclipse version is 4.10.0

**Comment by martinlippert** [comment]
This is very much likely a bug in Eclipse, so please file this as a bug report to https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT, attach the full stack trace and a small sample project that helps them to reproduce the problem. Also testing this against the latest Eclipse version (2019-03 released today) might help in order to avoid submitting a bug that has already been fixed.

STS 4.2.0 will be available soon and will be based on Eclipse 2019-03, in case that release already contains the fix.
