### ISSUE TITLE
Plug-in org.eclipse.jdt.ui was unable to load class org.eclipse.jdt.internal.ui.packageview.PackageExplorerPart.

### ISSUE THREAD

**Issue by bbehera277** [spring-projects/spring-ide#423]
I am getting this error when opening any workspace in my STS 3.9.5.. PLease find the snap. I've been facing this issue from past 4 days, not getting any solution.
![STS error](https://user-images.githubusercontent.com/76647449/104832507-8e06c580-58b7-11eb-9158-640af9a87386.PNG)

**Comment by martinlippert** [comment]
This looks a lot like an incompatibility between the used Eclipse base version and the installed STS3 components. It looks like you are using an STS3 distribution. Which version do you use? If that really `3.9.5` (which is quite old)? And did you update anything or do you use an unchanged STS3 distribution?

You could also try to download the latest version of the STS3 distributions from here: https://github.com/spring-projects/toolsuite-distribution/wiki/Spring-Tool-Suite-3, if you want to start with a fresh and ready-to-use installation of the STS3 distribution.

Please also keep in mind that you should think about switching to the new Spring Tools 4 for Eclipse instead of this old STS3 distribution. And if you still want to use STS3, please tell us why and what you are missing from the Spring Tools 4 in order to be a useful replacement for your current STS3 install.

**Comment by bbehera277** [comment]
The incompatibility you are talking about, please be informed that I've been using the same version of STS (i.e 3.9.5) for quite few years seamlessly(around 3-4 years). How come suddenly the incompatibility issue will occur ? And I didn't updated or changed  anything to the same.

By the way, I tried 3.9.15, however that didn't supported in my system(32-bit windows 8). So for that I don't think spring tools 4 will support as there is no 32-bit version I found.

And most important thing I would like to inform you that, this morning I tried completely new workspace setup in a different directory, that is working fine. So I thing some configuration is missing(I don't understand how it happened as well, as I didn't do any R & D on STS)

**Comment by martinlippert** [comment]
> The incompatibility you are talking about, please be informed that I've been using the same version of STS (i.e 3.9.5) for quite few years seamlessly(around 3-4 years). How come suddenly the incompatibility issue will occur ? And I didn't updated or changed anything to the same.

That is indeed very strange. No idea why that problem showed up suddenly.

> By the way, I tried 3.9.15, however that didn't supported in my system(32-bit windows 8). So for that I don't think spring tools 4 will support as there is no 32-bit version I found.

Okay, understand. We indeed do not support 32-bit installs anymore with Spring Tools 4 or newer versions of STS3.

> And most important thing I would like to inform you that, this morning I tried completely new workspace setup in a different directory, that is working fine. So I thing some configuration is missing(I don't understand how it happened as well, as I didn't do any R & D on STS)

It sounds at least like you can resolve this by using a new workspace and re-importing your projects into that new workspace. Would that work for you?

In addition to that it would be interesting to the some more details about the error. I can see that the problem shows up in your Error Log view. Please open the errors and add the stack traces here. Maybe that gives us a better understanding of what is going wrong here.

**Comment by bbehera277** [comment]
Hi Martin, Thanks for your earliest responses so far. And yes, I resolved this by using a new workspace and re-importing my project into that new workspace & that worked for me.

Since unfortunately I've deleted that corrupted workspace after creating a new one(as I was frustrated with that), I am unable to share that error stack traces. The only screenshot(attached initially) I have as an evidence to the error.

But in case in future I'll get the same issue again....I will definitely post here.
