### ISSUE TITLE
Boot dash concurrent modification exception

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-ide#73]
Workspace doing a big daily rebuild:

```
An internal error occurred during: "Refresh Launch Conf Boot Dash Elements".
java.util.ConcurrentModificationException
```

**Comment by martinlippert** [comment]
Do you have a stack trace for this one? Maybe in the Error Log somewhere? That would be great.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Nieraj Singh:) 

As far as I can tell, this problem appears to have been fixed already by this:

https://www.pivotaltracker.com/story/show/123506701

The stack trace above indicates that this issue was encountered on an older STS, as the potential ConcurrentModificationException at this location in the old code:

```
at org.springframework.ide.eclipse.boot.dash.util.LaunchConfigurationTracker$2.run(LaunchConfigurationTracker.java:109)
```

is in the wrong synchronized block in the old code.

In the newer code, line number 109 does not point to anything that can cause ConcurrentModificationException, and in the new code, this iteration over the HashMap is in a correct synchronized block.

I can't reproduce this with STS 3.8.3 , and after consulting with Kris, I will mark it as already fixed.
