### ISSUE TITLE
Parts of Template Proposal Area Greyed out in Linux(Ubuntu)

### ISSUE THREAD

**Issue by Raj-Kishan** [spring-projects/spring-ide#91]
When i press ctrl+enter for proposals, i get the window fine. But the top, right and bottom parts of the box are greyed out. So, i cannot see the texts in those areas.

Sample Image of what i mean;

![greyed_template_field](https://cloud.githubusercontent.com/assets/11648446/22873744/fd256452-f1e7-11e6-984f-2c1798b04fac.jpg)

Please note that the box is not transparent. But when i took print screen, it appeared so.

**Comment by martinlippert** [comment]
Hmmm, this looks very specific to Ubuntu. Which version of Ubuntu are you using? The Eclipse support for Linux GTK is somewhat fragile with regards to the version of Linux and specifically the version of Ubuntu that is being used. Can you also try to run pure Eclipse (just to verify that this is a problem with the Eclipse Linux support)? And maybe also try one of the latest Eclipse Oxygen builds from the downloads? Maybe that is something that got fixed in the meantime.

You could also try to switch back to the GTK2 support (which isn't better in general, but might not have that specific issue that you came across): https://bugs.eclipse.org/bugs/show_bug.cgi?id=430736#c50

**Comment by Raj-Kishan** [comment]
Found the reason. It is cause of `Ultra-Flat-Theme` in linux. After i changed the theme to default, problem disappeared. Thank You.

**Comment by martinlippert** [comment]
Glad to hear that you found the reason for the issue and thanks for letting us know.
